services:

  db:
    hostname: db
    image: postgres:16
    volumes:
      - user-mgmt-api-db-data:/var/lib/postgresql/data

      # Seed the database and records during initial startup. Will not run if the volume is already populated
      - ./sql:/docker-entrypoint-initdb.d

    restart: always
    environment:
      # Local env only
      POSTGRES_PASSWORD: test
      POSTGRES_DB: user-mgmt-db

  webserver:
    hostname: server
    build:
      context: .
      args:
        BUILD_VERSION: "${BUILD_VERSION}"

    ports:
      - "${HOSTPORT}:8080"

    environment:
      LOG_LEVEL: debug
      RUNNING_LOCALLY: true
      database_host_name: db
      database_port: 5432
      database_name: user-mgmt-db
      database_username: postgres
      database_password: test
      database_ssl_mode: disable

    depends_on:
      - db

volumes:
  user-mgmt-api-db-data: