# Image used for seeding the database during E2E tests
FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /sql-scripts
COPY ../sql/* /sql-scripts

COPY ./db-seed/entrypoint.sh /
RUN chmod a+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
