name: CI
on:
  push

permissions:
  id-token: write   # required for requesting the JWT
  contents: read    # required for actions/checkout

jobs:
  ECRUpload:
    runs-on: ubuntu-latest
    env:
      AWS_REGION : "eu-west-2"
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::633681147894:role/gh-actions-user-mgmt-service-api-workflow
          role-session-name: GHActions-user-mgmt-service-api
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Required for multi-platform builds
      # https://docs.docker.com/build/ci/github-actions/multi-platform/
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

# I shouldn't need this for cross compilation builds
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3

      - name: Build & push multi-architecture Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: user-mgmt-service-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform linux/amd64,linux/arm64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          platforms: linux/amd64,linux/arm64
#          load: true
#          tags: ${{ steps.login-ecr.outputs.registry }}/user-mgmt-service-api:${{ github.sha }}