name: CI
on:
  push
env:
  BUCKET_NAME : "mike-test-72972"
  AWS_REGION : "eu-west-2"
permissions:
  id-token: write   # required for requesting the JWT
  contents: read    # required for actions/checkout
jobs:
  S3Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::633681147894:role/gh-actions-user-mgmt-service-api-workflow
          role-session-name: GHActions-user-mgmt-service-api
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload file to S3
        run: |
          aws s3 cp ./README.md s3://${{ env.BUCKET_NAME }}/